[package]
name = "wikipedia-word-counter"
version = "0.1.0"
authors = ["Alec Larsen <hello@alec.ninja>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
regex = "1.3.6"
crossbeam-channel = "0.4.2"
parse_mediawiki_dump = "0.1.0"
parse_wiki_text = "0.1.5"
csv = "1.1.3"
